# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wonyoung Park
title: Gachon University, TEAMLAB 학부생 연구원
email: holly31521@gmail.com
website: https://www.notion.so/Wonyoung-Park-662a88460461455e8063b684c7957a61
phone : 010-6782-7781

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Wonyoungpark
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요 박원영입니다.<br>
  수많은 0 중에서 유의미한 <mark>1</mark> 로 되고 싶습니다.
# skilled in: <mark>Python</mark>, <mark>Django</mark> and <mark>Eating Pizza</mark>
  
  엔지니어가 되기 위한 지속적인 <mark>자기 개발</mark>
    - 학습한 공부 내용 공유 <a href="https://github.com/Wonyoungpark/TIL" target="_blank"> Today, I Learned </a>
    - 외국어 능력 향상을 위한 영어 쉐도잉

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: WA3I-Automated-Scoring
        # link_text: Project Website
        github: TeamLab/WAI-Automated-Scoring
        link: http://wai.best/
        additional_links:
          - title:  인공지능과 서술형 
            icon: fab fa-youtube
            url: https://www.youtube.com/embed/20h195JbXSQ
          - title:  notion/WA3I-Automated-Scoring
            icon: fas fa-link
            url: https://www.notion.so/WAI-Project-4ab740fd57c1426ba422dfda4dfba07b
        quote: >
          창의성 개발을 위한 서술형 지원 AI 프로그램 개발
        description: | # this will include new lines to allow paragraphs
          - 프로젝트 기간 : 2020.03 - 2020.12 <br>
          - 지원 기관 : <a href="https://lms.kofac.re.kr/front/main/index.do" target="_blank"> 한국과학창의재단 </a><br>
          - 사용자 기능 정의 및 화면 설계서 작성<br>
          - 프로젝트 DB 설계 및 개발<br>
            - MySQL, SQLite<br>
          - 웹 페이지 개발<br>
            - Django : web front-end와 back-end 개발<br>
            - Bootstrap, HTML, css, jQuery, Ajax, DataTables : web front-end 개발<br>
            - Python : request 데이터 처리, 채점 모델 API 연결<br>
            - Docker : 시스템 구축 및 실행<br>
            
      - layout: top-middle
        title: Codeborn-Autograding
        # link_text: Project Website
        github: Wonyoungpark/codeborn
        additional_links:
          - title:  notion/Codeborn-Autograding
            icon: fas fa-link
            url: https://www.notion.so/Codeborn-Autograding-7163b70b739d4ef8b994c48f7964b6b2
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          AI 자동 채점 지원 프로그램 개발
        description: | # this will include new lines to allow paragraphs
          - 프로젝트 기간 : 2020.08 - Present <br>
          - 지원 기관 : <a href="http://theteamlab.io/" target="_blank">TEAMLAB</a><br>
          - 사용자 기능 정의 및 화면 설계서 작성<br>
          - 프로젝트 DB 설계 및 개발<br>
            - MySQL<br>
          - DB 배포<br>
            - Express<br>
          - 웹 페이지 개발<br>
            - Node.js : web back-end 개발<br>
            - Vue.js : web front-end 개발<br>
          - 채점 모델 개발<br>
            - AWS LABMDA를 사용한 채점 모델 (REST API)<br>
            - Docker 기반 채점 모델 <br>
          - Docker 기반 시스템 작동 (Web, DB, 채점모델 등)<br>
          - 웹 페이지 Test Scenario 작성<br>
      
      - layout: top-middle
        title: TEAMLAB_2019_WinterStudy 프로젝트
        # link_text: Project Website
        github: Wonyoungpark/teamlab_2019_winter
        additional_links:
          - title: winter project
            icon: fas fa-link
            url: https://github.com/Wonyoungpark/teamlab_2019_winter
        quote: >
          Naver 웹툰 연동 사이트
        description: | # this will include new lines to allow paragraphs
          - 프로젝트 기간 : 2020.01 - 2020.02 <br>
          - 지원 기관 : <a href="http://theteamlab.io/" target="_blank">TEAMLAB</a><br>
          - 사용자 기능 정의 및 화면 설계서 작성<br>
          - 프로젝트에 필요한 데이터 수집 및 분석<br>
            - Python, crontab : Crawling 코드 작성 및 자동화<br>
              - Pandas, Numpy, Selenium, Beautifulsoup..<br>
          - 프로젝트 DB 설계 및 개발<br>
            - MySQL, pymysql<br>
          - 웹 페이지 개발<br>
            - Django : web front-end와 back-end 개발<br>
            - Bootstrap, HTML, css, jQuery, Ajax : web front-end 개발<br>
            - Python : request 데이터 처리<br>
            - AWS - EC2(Linux-Ubuntu) : 시스템 실행<br>
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TEAMLAB
        link: 
        # link_text: boringcompany.com
        sub_title: Undergraduate Researcher
        caption: September 2019 - February 2021
#         quote: >
        description: | # this will include new lines to allow paragraphs
          [![teamlab link](/images/teamlab.png "teamlab"){: width="50%" height="50%"0}{: align="center"}](http://theteamlab.io/)
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Gachon University, Korea
        caption: 2018 - Present
        sub_title: Bachelor of Engineering
#         quote: >
        description: | # this will include new lines to allow paragraphs
          Major : Industrial Management Engineering<br>
          Double Major : Computer Science<br>
          GPA : 4.09/4.5 <br><br>
      - layout: left
        title: University of Hawai'i at Manoa
        link: https://manoa.hawaii.edu/
        caption: 2020.01.06 - 2020.02.02
#         sub_title: Bachelor
#         quote: >
        description: | # this will include new lines to allow paragraphs
          지원기관 : [Gachon University, Korea](https://www.gachon.ac.kr/index.html, "가천대학교 link")<br>
          Program : 2019-동계 Hawaii Gachon Elite Course
          
#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
